### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#1]
**Objetivo**

Disponer de un slider para poder ver las escenas de película

**Pasos a seguir**

1. Crear un componente. Este componente recibe un conjunto de imágenes. Esta propiedad podria ser un array de strings, donde cada string es una URL.
2. El componente muestra una de las imágenes.
3. Debe existir un método para poder cambiar la imagen visible en todo momento
4. El slider debe poder acumular imágenes. Debemos poder iterar entre todas ellas a través de un control similar a los que ofrece bootstrap: https://getbootstrap.com/docs/5.1/components/carousel/#with-indicators
5. Las imagenes las ponemos en la carpeta 'public'. Sería interesante buscar algunas imagenes de escenas de una misma película

**Criterios de aceptación**

**Comment by omiras** [comment]
@ardelgad @LilaSarfson Sería interesante que por defecto, siempre se muestre **la última imagen** del slider por defecto. De esta manera, cada vez que añadamos una escena de la peli nueva porque el usuario ha fallado, siempre vamos a mostrar la última imagne añadida, y el usuario podrá iterar por todas ellas a través de los números

**Comment by ardelgad** [comment]
### Instrucciones de Testeo
- Te debería aparecer _solo_ una imagen y un botón apenas se carga la página.
- Si te equivocas se añade una nueva imagen al array y se muestra por pantalla con su botón correspondiente. Por defecto, se debería mostrar siempre la última imagen del array.
- Todos los botones nos deberían permitir ir a su imagen correspondiente y al pasar por encima el circulo debe cambiar de color.
- Si aciertas la letra no se debería añadir ninguna imagen nueva.

**Comment by ArantxaDelgado** [comment]
# Instrucciones de Testeo
- Te debería aparecer _solo_ una imagen y un botón apenas se carga la página.
- Si te equivocas se añade una nueva imagen al array y se muestra por pantalla con su botón correspondiente. Por defecto, se debería mostrar siempre la última imagen del array.
- Todos los botones nos deberían permitir ir a su imagen correspondiente y al pasar por encima el circulo debe cambiar de color.
- Si aciertas la letra no se debería añadir ninguna imagen nueva.
