### ISSUE TITLE
Entrada de texto por teclado

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#13]
**Objetivo**

Poder usar el teclado para adivinar las letras de la película

**Análisis Técnico**

1. Entender el App.vue: cómo usa los componentes
2. Asociar el evento 'keyup' a todo el App.vue 
3. No todas teclas me valen. Hay que procesar solo las taclas que son letras, da igual si mayúscula o minúscula.
  1. Versión bonus: mirar si esto sale bien con un Regex
5. Si pasa todos los filtros, llamar al método letterClicked(letter)

**Comment by VCabelloDel** [comment]
**Instrucciones de prueba**
- Primero debemos tener el focus en el main de la página. Entonces la aplicación escucha el teclado y inserta la tecla dentro del panel de letras.
- No importa si escribes en mayúsculas o minúsculas. 
- Tampoco si pulsa alguna tecla que no sea una letra. No debería plasmarse en la pantalla en ninguno de los casos.
- Conserva todas las funcionalidades del teclado virtual en cuanto a estilos y demás.

**Comment by rayaalmudena** [comment]
Al presionar una letra, enviarla con toLowerCase (si no, hace pum)
this.letterClicked(keyPressed.toLowerCase());
