### ISSUE TITLE
Jugabilidad: juego base

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#17]
**Objetivos y análisis técnico**

1. Los jugadores tienen un número determinado de intentos para resolver el ahorcado
2. Si han adivinado todas las letran han ganado. Aparecerá el modal con una imagen del array a toda pantalla . Además aparecerá la paloma Carmen alegre. Botón de reset.
3. Los intentos son "palomitas". Hay que poner claramente que las palomitas representan intentos, con un texto. Intentos: 🍿 🍿 🍿 🍿 🍿 
4. Si nos quedamos sin palomitas, aparecerá un modal, con la paloma Carmen _triste_, sin la imagen de la peli, pero con un mensaje de ánimo para que vuelvan a intentarlo (botón de reset) (window.location.reload())
5. Nueva computed property que haga que solo se muestre el teclado solo si todavía estamos jugando. Además, hay que hacer "return" al procesar el keyup si ya hemos terminado el juego. (podeis consultar la computed property como si fuera una función)

**Comment by rayaalmudena** [comment]
He encontrado esto en stackoverflow [here](https://stackoverflow.com/questions/40649681/how-to-check-if-a-string-contains-all-the-elements-of-an-array-in-javascript)


```
var str = 'apple_mango_banana';
var arr = ['apple','banana'];

var isEvery = arr.every(item => str.includes(item));

console.log(isEvery);
```

**Comment by Akitetsuk** [comment]
# Problemas que hemos encontrado 

- Como los puntos se ponían hacia dentro. La clase popcornPoints tiene un tamaño fijo en pixeles . Hemos probado varias maneras , pero la manera más efectiva es esta, pero al redimensionar la pantalla siempre quedara fijo , siempre y cuando la pantalla mida más de los pixeles puestos.

- Faltaría poner un contorno al logo ya que si la imagen es blanca no sé ve correctamente el logo.

**Comment by Akitetsuk** [comment]
# Instrucciones: 

- Cada vez que falles una letra del titulo de la película veras que desaparecen las palomitas (Los puntos que tienes).
- Para ver la pantalla final de derrota falla 5 letras y saldrá la paloma Carmen con un mensaje.
- Para ver la pantalla final de victoria acierta el titulo de la película y saldrá la paloma Carmen con un mensaje.
- Prueba el botón de la pantalla final que pone "Volver a jugar" tendría que hacer una recarga de la pagina (un f5 automático) .
- Si le das a la X de la pantalla del modal (donde esta la paloma Carmen) se cerrada el modal , desaparecerá el teclado y veras que aumentado el tamaño de la imagen del slider.
- Si cierras el modal veras que no puedas pulsar por teclado ninguna tecla.

**Comment by Akitetsuk** [comment]
# Implementar 
- El mensaje de la paloma tiene que tener multi idioma.
