### ISSUE TITLE
Rules & About Us

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#18]
**Objetivos**

Rules.vue

1. Escribir las instrucciones del juego siguiendo el estilo de [Wordle](https://wordle.danielfrg.com/)
2. Traducir las instrucciones al catalán y español en el fichero main.js. 
3. Implementarlo en el componente components/pages/Rules.vue

Info.vue

1. Escribir quiénes somos, que hemos hecho y porque.
2. Enlaces a Github, Landing Page y página Linkedin del equipo

**Comment by omiras** [comment]
Renombrad los componentes para que cumplan la guía de estilo :)

**Comment by omiras** [comment]
Poned por favor también las traducciones 😄

**Comment by ArantxaDelgado** [comment]
Todo funciona correctamente 🥇 Felicidades 😺
