### ISSUE TITLE
FilmReel

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#2]
**Objetivo**

Ocultar el título de la película e irlo revelando a medida que el usuario acierta las letras.

**Pasos a seguir**

1. El componente debe poder recibir una película. El componente debe poder recibir una letra.
2. Debe cargar tantas casillas de film como letras tiene la película
3. Allí donde haya un espacio en blanco porque hay separación de palabras; simplemente lo pintamos de negro (o color sólido, pero dibujamos igual el reel)
4. Si el componente recibe una letra que es parte de la película, debe revelarla.
5. Valorar animación cuando se revele la tecla

**Criterios de aceptación**
- Al cambiar la variable title del App.vue debería escribirse el titulo de la película.
- Al introducir las letras en el array guessedLettersMayus deberían revelarse en el titulo

**Comment by nexus122** [comment]
Podemos utilizar esta [animación ](https://www.w3schools.com/howto/howto_css_flip_card.asp)para cada vez que se descubre una letra

**Comment by omiras** [comment]
- Cuantos carácter de máximo debería tener una película? 20 carácteres
- Lo dividimos por palabras

**Comment by nexus122** [comment]
## Puntos a mejorar y dudas:
 - Ahora mismo estamos partiendo los espacios para generar nuevas filas, pero en películas como: quien ama a gilber grape quedan demasiadas filas, necesitaríamos saber cuantos caracteres como máximo tiene una fila y como partir palabras a medias.
 - Mejorar la animación con lo que aprendimos ayer de animaciones en Vue

**Comment by nexus122** [comment]
# Instrucciones de testeo
- Poner el titulo de la película en la variable movie .
- En el titulo no importa si se ponen minúsculas o mayúsculas. 
- Cuando pongamos el titulo de la película nos cargara unas casillas conforme las palabras que lo forma ejemplo: Star wars cargaría XXXX XXXX. 
- Cuando se clica una letra del teclado y esta se muestra en el panel mediante una animación para mostrarla Ejemplo clicamos la T entonces pondría XTXX XXXX . 
- Si la letra no esta , no habrá animación y el tablero se quedara igual ejemplo clicamos la Q el tablero se quedara  XTXX XXXX . 
- El texto no se puede seleccionar.
- Separamos el texto por palabras y no deberían cortarse por la mitad.

**Comment by ArantxaDelgado** [comment]
Súper! Todo funciona estupendamente :)
