### ISSUE TITLE
Bug: películas concretas no funcionan

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#22]
Pasos a reproducir
-Abrimos la página, dispuestos a jugar.

¿Qué debería pasar?
-Deberíamos poder jugar.

¿Qué pasa en realidad?
-Por algún motivo, algunas películas concretas se cargan la app entera, como Curro Jiménez y alguna más. En estos casos, no aparecen las letras a adivinar y el teclado virtual se buggea, apareciendo como una colección de rectángulos de color rojo.

**Comment by VCabelloDel** [comment]
RESUELTO:

Las películas que fallaban eran realmente series, por lo que sus propiedades dentro del array de películas eran distintas. La app intentaba recuperar sus datos sin éxito, lo que provocaba el error.

Hemos eliminado las tres series de la lista de TMDB para prevenir el error. Si en el futuro se quisieran incluir series, habría que modificar el código para que tuviese en cuenta el nombre de las propiedades de las series.
