### ISSUE TITLE
La letra Ñ no funciona

### ISSUE THREAD

**Issue by ArantxaDelgado** [Singulars2022/cinedebarrio#24]
### Pasos a reproducir
- Buscar una pelicula que tenga una (o mas) ñ en el título y empezar a resolverla.

### ¿Qué debería pasar?
- Se devería desvelar toda la palabra sin ningún error y marcandote como incorrectas solo aquellas letras que lo són

### ¿Qué pasa en realidad?
- No identifica la Ñ: la marca como incorrecta y no siempre la enseña

<a href="https://ibb.co/fXZjFRh"><img src="https://i.ibb.co/p1NYwDt/Captura-de-pantalla-4.png" alt="Captura-de-pantalla-4" border="0"></a>
<a href="https://ibb.co/VLpxKtp"><img src="https://i.ibb.co/2FYSbyY/Captura-de-pantalla-5.png" alt="Captura-de-pantalla-5" border="0"></a>
<a href="https://ibb.co/SXFch86"><img src="https://i.ibb.co/nsxBHvw/Captura-de-pantalla-6.png" alt="Captura-de-pantalla-6" border="0"></a>

**Comment by Akitetsuk** [comment]
Va correctamente falta hacer "el merge" ya que carga una película en especifico

**Comment by omiras** [comment]
¡Hola! . ¡ Buen trabajo ! Recordad de no hacer directamente un **merge** in consultar antes 😸 

El nombre de la rama es más adecuado: 27-issue-que-es-lo-que-pasa.
