### ISSUE TITLE
Introducir letra nueva

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#3]
**Objetivo**

Poder introducir una letra desde la interfaz de usuario

** Pasos a seguir **

- Opción 1: Buscar un componente Vue de teclado virtual 
- Opción 2: Crear un carousel de letras
  1. Se muestra un carousel de letras inicializado con la letra 'A'
  2. Existen dos flechas para poder iterar entre las letras del abacedario
  3. Con la rueda del ratón, se puede iterar por las letras de manera más rápida
  4. Al hacer click encima de la letra, debemos poder recuperar dicha letra
  5. La letra clicada desaparece del carousel de letras
  6. Pensar como mejorar la experiencia de usuario para: Indicar claramente que  se puede pulsar, y visualizar más de una letra para dar la información inequívoca de que se puede iterar entre todas ellas.

**Comment by omiras** [comment]
- Vueficar el componente y cambiar los spans por botones.

**Comment by RaulHinojosa24** [comment]
# Uso del componente
## Descripción
El componente recibe un array de arrays (cada array es una línea del teclado) con todas las letras que se quieren en el teclado. 
Y cuando el usuario clica en una letra, el componente emite ésta.

## Detalles técnicos de uso
En el componente padre, hay que hacer un map previo y añadirle a cada letra las siguientes propiedades:
 - id: una id única
 - letter: la letra del teclado
 - status: para controlar los estilos de la tecla (poner "default" como predeterminado)

Cuando clickemos la letra en el teclado, recibiremos un emit "clickedLetter" con el parámetro "id" de la letra.

En en momento de la comprobación de si la letra es correcta o no, usaremos la "id" del emit para modificar el "status" de la letra pulsada. Le pondremos:
 - "wrong" - si la letra NO es correcta
 - "correct" - si la letra SI es correcta

En función del "status" el Keyboard le pondrá un estilo acorde. (éstos se pueden cambiar en el <style> del componente)
