### ISSUE TITLE
Posbles mejoras diseño:

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#39]
- Ver que la app se vea bien en Edge
- Conseguir que la app se vea bien en versión móvil
- Evitar en lo posible que aparezcan scrolls. Quizás reducir el gap un poco entre elementos del flex vertical. Que se vean los intentos en el 90% de las pelis.
- Eliminar reglas CSS no utilizadas
- El hoover del componente "About Us" hace que todo el contenido se cambie a rojo
- Usar otros iconos para las reglas y el about us. Mirar en https://fontawesome.com/search?s=solid%2Cbrands o considerar poner directamente el texto (Instrucciones, Quienes somos?)
- El contenido de "About Us" no está centrado
- Valorar si la directiva v-cloak puede ser usada para que no sea vea momentáneamente la carga de un componente (sobretodo ocurre al iniciar la app)

**Comment by omiras** [comment]
- Cambiar el favicon
- Cambiar a Carmen informativa
- #32 En este issue hay unos cambios propuestos por Raúl para poder hacer el dark theme/ light theme. Revisarlo y aplicarlo.
- Poner un contenedor algo transparente debajo del teclado que también abarque los intentos

**Comment by kcarvajals** [comment]
Posible solución para el scroll: html, body {margin: 0; height: 100%; overflow: hidden}
