### ISSUE TITLE
Página principal

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#4]
**Objetivo**

Definir el aspecto inicial de la App

**Pasos a seguir**

1. Añadir el logo en la página (donde sea). Crear un componente Logo.vue
2. Aplicar en <style> todos los esitlos globales de la app
3. Configurar las variables CSS adecuadamente con los colores del diseño gráfico
4. Crear un control del tipo 'toggle' para cambiar de modo oscuro a claro y viceversa

**Comment by omiras** [comment]
Añadir [Normalize](https://necolas.github.io/normalize.css/)a los estilos generales

**Comment by omiras** [comment]
- Mirar que todo lo implementado se vea bien (mirar los CSS de los componentes)

**Comment by omiras** [comment]
Vamos a intentar instalar Vuetify para usar sus componentes y su cambio de modo oscuro a modo claro, hover de elementos, etc

**Comment by RaulHinojosa24** [comment]
He implementado un theme toggler, a ver qué os parece
