### ISSUE TITLE
Origen de datos: Bilbiotecas y herramientas para el proyecto:

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#5]
**Info notas**

- API de escenas de películas o vamos a tener que crear nosotros una 'base de datos' https://framed.wtf/
- Investigar si Spotify podria proporcionarnos musica de películas a través de su API
- Investigar cual seria el set interesante de películas españoles/internacionales para ofrecer a la generación actual de abuelos/as. a Partir del 1960 aprox

**Objetivo**

1. Cada vez que se cargue la página, aparece una película nueva a adivinar
2. La película a adivinar debe tener menos de 30 carácteres

**Análisis técnico**

1. Modificar App.vue para que, cada vez que se inicie la aplicaicón, inicialice PanelLetters.vue con una película nueva
2. El sitio más adecuado para implementar esto quizás es el hook created o mounted.
3. Seguramente esta funcionalidad va a ser reutilizada, así que saltándonos un poquito XP, podemos poner este funcionalidad dentro de una función (método), algo así como **resetGame**

**Comment by omiras** [comment]
Creo que como primer prototipo a lo mejor tampoco hay que preocuparse demasiado del origen de datos. Quiero decir, quizás es suficiente con crear un JSON a mano, con unas 100 películas españolas entre los años 60 y 90, y algunas americanas muy famosas. No creo que jueguen 100 veces en el casal los mismos abuelos al juego (ojalá!).

Por cierto, usando el localStorage podriamos asegurarnos que esas 100 películas, nunca se repitan en un mismo equipo ;)

**Comment by omiras** [comment]
- Las tildes deben verse en el nombre de la película pero no hay que pulsarlas explícitamente.
- Si hay guinones, o comas, u otros signos de puntuación, aparecerán como letra revelada sin necesidad de escribirlos.

**Comment by omiras** [comment]
Cómo obtener la imagen de las películas: https://github.com/omiras/hangman-ajax-app/blob/main/scripts/request.js

**Comment by omiras** [comment]
Podéis el hook created() como punto adecuado para hacer la petición a la API

**Comment by omiras** [comment]
- Traer la película y pasarla a la variable _movie_
- Las dos imágenes, ponerlas en un array de string, y es la variable _movies_ (quizás cambiar a movieImages). De momento, obtened las dos imágenes que ya os proporcionan siguiendo el ejemplo de hangman-ajax-app

**Comment by nexus122** [comment]
## problemas que hemos encontrado 

- Nos encontramos el problema que a veces solo nos devuelve una imagen, y a veces esa es el poster que tiene el nombre incluido.
- El tamaño del slider es más grande que la propia imagen
- La imagen 2 si hay cuando tendría que aparecer? (Ahora esta de manera fija pone el número de las imágenes y se tiene que ir pulsando para cambiarla)

**Comment by nexus122** [comment]
## Intrucciones:

- Hacer f5 para poder ver que va cambiando de película tanto el titulo como la imagen.
- Los caracteres especiales como guiones, puntos, exclamaciones..  Deben aparecer revelados.
- Al pulsar una letra debe revelarla aunque tenga acento.

**Comment by omiras** [comment]
> ## problemas que hemos encontrado
> * Nos encontramos el problema que a veces solo nos devuelve una imagen, y a veces esa es el poster que tiene el nombre incluido.

Sí, esto es algo que ya veníamos viendo. Me pregunto cuan viable es utilizar estas imágenes para nutrir la app.
Dos alternativas:

1. Buscar 3 imágenes por película, "a mano", y ponerlas en la carpeta "public". relacionarlas a partir de su ID. es un trabajo pesado, sí, pero efectivo
2. Buscar otra API que nos proporcione imágnes a partir del título de una película
3. Existe un software para eliminar texto de las imágenes que se pueda usar en nuestra app?

**Comment by Akitetsuk** [comment]
Decidir cuántas imágenes poner .
Cuando ponerlas (por número de fallos y cuántos por ejemplo fallo 3 veces sale la 2n imagen  o cuando el usuario quiera más pistas)

Si, se hace de manera manual habrá 300 imágenes mínimo. Saldría viable? (Peso de la aplicación).

**Comment by Akitetsuk** [comment]
> > ## problemas que hemos encontrado
> > 
> > * Nos encontramos el problema que a veces solo nos devuelve una imagen, y a veces esa es el poster que tiene el nombre incluido.
> 
> Sí, esto es algo que ya veníamos viendo. Me pregunto cuan viable es utilizar estas imágenes para nutrir la app. Dos alternativas:
> 
> 1. Buscar 3 imágenes por película, "a mano", y ponerlas en la carpeta "public". relacionarlas a partir de su ID. es un trabajo pesado, sí, pero efectivo
> 2. Buscar otra API que nos proporcione imágnes a partir del título de una película
> 3. Existe un software para eliminar texto de las imágenes que se pueda usar en nuestra app?

Decidir cuántas imágenes poner .
Cuando ponerlas (por número de fallos y cuántos por ejemplo: fallo 3 veces sale la 2n imagen o cuando el usuario quiera más pistas)

Si, se hace de manera manual habrá 300 imágenes mínimo. Saldría viable? (Peso de la aplicación).

Para eliminar el texto del póster se podría jugar con la opacidad o el zoom ? (Manera de solo tener una imagen que nos la proporciona la API y no tener 300 en la carpeta "public')

Añado también que daría más pistas si fueran imágenes de las películas ya que mucha gente no conoce los cárteles.
