### ISSUE TITLE
Crear componente modal

### ISSUE THREAD

**Issue by omiras** [Singulars2022/cinedebarrio#7]
**Objetivo**

Para diversas partes de la app (instrucciones, elegir equipo, información del proyecto); se requiere de una funcionalidad modal.
Crear un componente encargado de albergar cualquier contenido interno como una ventana normal puede ser la mejor aproximación.

**Análisis técnico**

1. Crear un nuevo componente (Modal.vue?). Se trata de crear un componente HTML/CSS modal, que además, pueda recibir cualquier tipo de contenido para mostrar. Podemos conseguir esto gracias a los [slot](https://vuejs.org/guide/components/slots.html#slot-content-and-outlet).
2. Crear el modal de 0, o seguir los pasos de buenos portales de referencia como [digitalocean](https://www.digitalocean.com/community/tutorials/vuejs-vue-modal-component). Alternativamente, también se puede buscar un componente modal en [NPMJS ](https://www.npmjs.com/) o  en[ Awasome Vue](https://github.com/vuesomedev/awesome-vue-3)

**Comment by omiras** [comment]
Añado: haced la página de instrucciones de cómo jugar ( solo modo solitario).

Mirad como usar dynamic components con Vue: https://vuejs.org/guide/essentials/component-basics.html#dynamic-components

**Comment by omiras** [comment]
- Hicierais el componente más parecido al ejemplo de digitalocean
- Aplicar [dynamic components](https://vuejs.org/guide/essentials/component-basics.html#content-distribution-with-slots) para que cargue Info.vue o Rules.vue

**Comment by rayaalmudena** [comment]
# Guia para instalar y poner a punto el componente

Importar el componente "Modal": 
`import Modal from ".../Modal.vue";`

Importar el componente que se quiere meter en el modal: 
`import Component from ".../Component.vue";`

Crear las variables de estado: (nombres arbitrarios)
- `isModalVisible : Boolean` Controlará si el modal está visible o no
- `currentModal : undefined` Controlará qué componente estará dentro del modal

Crear 2 methods para controlar el modal:
```
openModal( modal ) {
    this.isModalVisible = true;
    this.currentModal = modal;
}
closeModal() {
    this.isModalVisible = false;
    this.currentModal = undefined;
}
```
openModal -> mostrará el modal y pondrá dentro el componente que le pases por parámetro
closeModal -> ocultará el modal y lo vaciará

Crearemos un elemento que al hacer click (por ejemplo), llamará a openModal(_componente_)
`<button @click="openModal(Component)">Open Component</button>`


Y creamos el elemento "Modal".
```
<modal :isModalVisible="isModalVisible" @close="closeModal">
    <component :is="currentModal" class="modal"></component>
</modal>
```
`isModalVisible` - Prop que recibe nuestra variable de estado que controla la visibilidad del modal.
`@close` - Cuando hagas click en la "x" del modal o fuera de éste, se ejecutará la función de `closeModal`
`<component :is="currentModal"/>` - Cambia dinamicamente el contenido del modal en funcion del valor de la varible "currentModal"

# Tests y pruebas de uso

1. Le das click al botón de abrir el modal
2. El modal aparece en medio de la pantalla
3. Le das click a la X o fuera del modal
4. El modal se cierra
5. Le das click a un segundo botón que abra el modal con otro contenido
6. Se repiten los puntos del 2 al 4 👍

**Comment by rayaalmudena** [comment]
Cambiar el position del modal a "fixed"
